### ISSUE TITLE
Expected input[32, 768, 3, 576] to have 3 channels, but got 768 channels instead.

### ISSUE THREAD

**Issue by edurenye** [samuelyu2002/pedestrian-traffic-lights#2]
Hi, I just set the correct paths to the annotations and to your datasets, I run the 'training.py' locally and I got the following error:

> RuntimeError: Given groups=1, weight of size 32 3 3 3, expected input[32, 768, 3, 576] to have 3 channels, but got 768 channels instead

Also a warning:

> UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.

**Comment by samuelyu2002** [comment]
For the runtime error, you may have to transpose the images such that the dimensions are (32, 3, 768, 576).

**Comment by ronaldosm** [comment]
> For the runtime error, you may have to transpose the images such that the dimensions are (32, 3, 768, 576).

Hi, If I transpose the images and execute 'training.py' using net = LYTNetV2 on line 30, I find this other error: `RuntimeError: Given input size: (960x9x12). Calculated output size: (960x0x1). Output size is too small`

**Comment by samuelyu2002** [comment]
Is this issue only for LytNetV2, or does it also happen in LytNetV1?
________________________________

**Comment by ronaldosm** [comment]
> Is this issue only for LytNetV2, or does it also happen in LytNetV1?
> […](#)
> ________________________________ From: Ronaldo da Silva Moura <notifications@github.com> Sent: Monday, March 16, 2020 10:34 PM To: samuelyu2002/ImVisible <ImVisible@noreply.github.com> Cc: Yu; Samuel <samuel01px2020@saschina.org>; Comment <comment@noreply.github.com> Subject: Re: [samuelyu2002/ImVisible] Expected input[32, 768, 3, 576] to have 3 channels, but got 768 channels instead. (#2) For the runtime error, you may have to transpose the images such that the dimensions are (32, 3, 768, 576). Hi, If I transpose the images and execute 'training.py' using net = LYTNetV2 on line 30, I find this other error: RuntimeError: Given input size: (960x9x12). Calculated output size: (960x0x1). Output size is too small — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsamuelyu2002%2FImVisible%2Fissues%2F2%23issuecomment-599570429&data=02%7C01%7Csamuel01px2020%40saschina.org%7C8b35a311e12645fb92a408d7c9b721ee%7Cd4c1f548d2494e72a7cb733b702e48d3%7C0%7C0%7C637199661321184921&sdata=vI0rYKhnyaaM3US8BWp6WNSXIels%2FtVcLAchBm8PVqA%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIMINVBE4LUGDMMP54KU65LRHY2HDANCNFSM4LD6B2FQ&data=02%7C01%7Csamuel01px2020%40saschina.org%7C8b35a311e12645fb92a408d7c9b721ee%7Cd4c1f548d2494e72a7cb733b702e48d3%7C0%7C0%7C637199661321184921&sdata=S9%2FrSAJjeXF3U63E7A%2FZlK9%2BS%2F02RyxHdn8hiKLj2I0%3D&reserved=0>.
I have this error: `RuntimeError: Given input size: (960x12x9). Calculated output size: (960x1x0). Output size is too small` 
only for LytNETV2

**Comment by samuelyu2002** [comment]
Can you show me the full error message - ie. what line the error is from?

**Comment by edurenye** [comment]
Thank you @samuelyu2002 transposing using `images = images.permute(0, 2, 3, 1)` does the trick, but now I'm getting another error:
`RuntimeError: Given input size: (960x9x12). Calculated output size: (960x0x1). Output size is too small`

But is strange that it just not run without errors, shouldn't it just work? I'm trying to train the model using your dataset, not custom images that might have diferent shapes. And changed `net = LYTNet()` for `net = LYTNetV2()` so it uses LYTNetV2. I'm doing something wrong? I just set the right paths to the files and call 'training.py'. Is LYTNetV2 not ready?

**Comment by edurenye** [comment]
With `net = LYTNet()` I get the same errors.

**Comment by samuelyu2002** [comment]
I checked the code and both LytNet and LytNetV2 should be correct. I suspect the issue was with the normalization in dataset.py, which I have commented out. Maybe try redownloading all of the code and running again, I think it should work now.

**Comment by edurenye** [comment]
Thank you @samuelyu2002 
Removed my changes pulled the new code and run again.
The original error about Expected input is fixed, but I still get the second error:
`RuntimeError: Given input size: (960x9x12). Calculated output size: (960x0x1). Output size is too small`

**Comment by samuelyu2002** [comment]
Is that error caused by the AvgPool2d on line 153? Maybe try using nn.AdaptiveAvgPool2d(1) instead. Or, try changing the nn.AvgPool2d(12,9) into nn.AvgPool2d(9,12).

**Comment by ronaldosm** [comment]
> Is that error caused by the AvgPool2d on line 153? Maybe try using nn.AdaptiveAvgPool2d(1) instead. Or, try changing the nn.AvgPool2d(12,9) into nn.AvgPool2d(9,12).

Using "nn.AvgPool2d (9,12)" fixed the error for me. Thank you!

**Comment by edurenye** [comment]
Yes, `nn.AvgPool2d (9,12)` fixes the error.
Now there is just a warning about a deprecation:
`UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.`

But it apparently works, I say apparently because after around 50 iterations on the first epoch the process dies without any error: `[1]    15411 killed     Model/training.py`

I'm using Ubuntu and python 3 to run it, I'll try to debug what it is, might be something about my local environment, I don't know.

Thank you very much for your help @samuelyu2002

**Comment by edurenye** [comment]
Apparently the process is slowly eating all my resources filling the 16GB of RAM and the 16GB of Swap until the kernel kills it. I never seen a neural network using so many resources, so there might be something wrong with the code.

**Comment by samuelyu2002** [comment]
The code does use a lot of RAM - maybe it is because the lists from line 41 to 51 in training.py are storing too many torch tensors. Try changing all of the values stored from torch tensors to normal floats - eg. on line 107 append running_loss_MSE.item() instead of running_loss_MSE.

**Comment by edurenye** [comment]
I don't think so, the ram increments on each step inside the epoch, and you append that data after every epoch, I run out of RAM and Swap before anything is stored on those arrays.

Until the moment I was trying it in the laptop and now I tried in my desktop and I have the same problem with the RAM. The thing is that in the desktop I did not have to change the `nn.AvgPool2d (9,12)`, it just worked, which is weird.

Anyway, I think the problem with the RAM might be related to the fact that I'm using CPU not GPU to train, because I don't have any GPU with CUDA. It should use more RAM, but not as much as it does.

**Comment by edurenye** [comment]
Seem to be a similar problem to this one: https://discuss.pytorch.org/t/cpu-ram-usage-increasing-for-every-epoch/24475

But there is no solution there.

Also from here: https://github.com/pytorch/pytorch/issues/27971 I tried to use `LRU_CACHE_CAPACITY=1` and from here: https://github.com/pytorch/pytorch/issues/13246 I tried to use `num_workers = 0` and none of them worked.

**Comment by samuelyu2002** [comment]
Try changing all of the places with += loss into += loss.item(). For example, change lines 97-99 into:
        running_loss += loss.item()
        running_loss_MSE += MSE.item()
        running_loss_cross_entropy += cross_entropy.item()
Also, change lines 165-167 into:
            val_running_loss += loss.item()
            val_mse_loss += MSE.item()
            val_ce_loss += cross_entropy.item()

The problem might be because the computational graphs were also being stored, taking up large amounts of RAM.

**Comment by edurenye** [comment]
Yes, that was it, now it works fine.

Thank you very much @samuelyu2002 !

**Comment by edurenye** [comment]
I see that you committed the changes, thank you!
